// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {platform} from '../models';
import {clean} from '../models';

export function CancelOperation():Promise<void>;

export function ListApps():Promise<Array<platform.AppInfo>>;

export function PreviewClean():Promise<Array<clean.PreviewEntry>>;

export function RunClean(arg1:boolean):Promise<string>;

export function RunOptimize(arg1:boolean):Promise<string>;

export function RunPurge(arg1:boolean):Promise<string>;

export function RunUninstall(arg1:string,arg2:boolean):Promise<string>;
