// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelOperation() {
  return window['go']['main']['App']['CancelOperation']();
}

export function ListApps() {
  return window['go']['main']['App']['ListApps']();
}

export function PreviewClean() {
  return window['go']['main']['App']['PreviewClean']();
}

export function RunClean(arg1) {
  return window['go']['main']['App']['RunClean'](arg1);
}

export function RunOptimize(arg1) {
  return window['go']['main']['App']['RunOptimize'](arg1);
}

export function RunPurge(arg1) {
  return window['go']['main']['App']['RunPurge'](arg1);
}

export function RunUninstall(arg1, arg2) {
  return window['go']['main']['App']['RunUninstall'](arg1, arg2);
}
