// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {analyze} from '../models';
import {status} from '../models';
import {platform} from '../models';
import {clean} from '../models';

export function AnalyzeDisk(arg1:string):Promise<analyze.Node>;

export function CancelOperation():Promise<void>;

export function GetStatus():Promise<status.MetricsSnapshot>;

export function ListApps():Promise<Array<platform.AppInfo>>;

export function PreviewClean():Promise<Array<clean.PreviewEntry>>;

export function RunClean(arg1:boolean):Promise<string>;

export function RunOptimize(arg1:boolean):Promise<string>;

export function RunPurge(arg1:boolean):Promise<string>;

export function RunUninstall(arg1:string,arg2:boolean):Promise<string>;
